// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDln5xHMA7Ve-ovCOdC6WK0mDYMKT7DfdU',
    appId: '1:481470008590:android:a8099e3a7b8cec725a9b5f',
    messagingSenderId: '481470008590',
    projectId: 'tinpet-fatec',
    storageBucket: 'tinpet-fatec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh7yOxebtc7ucNaqp6H3jiJcSF8_Ocjko',
    appId: '1:481470008590:ios:0c42810ec7b7c1065a9b5f',
    messagingSenderId: '481470008590',
    projectId: 'tinpet-fatec',
    storageBucket: 'tinpet-fatec.appspot.com',
    androidClientId: '481470008590-eip39j3mqdbtgrv6aeqfbvp1s5r6gbf0.apps.googleusercontent.com',
    iosClientId: '481470008590-aimu12p4h8khn5ead84tauef637enehu.apps.googleusercontent.com',
    iosBundleId: 'com.app.tinpet',
  );
}
